import React from "react";

function Sobre() {
  return (
    <section>
      <h2>Sobre o Programa</h2>
      <p>O programa busca a excelência na produção da carne e do leite gaúchos e a sua valorização pelos aspectos diferenciais do Rio Grande do Sul.</p>
      <h2>Funcionamento</h2>
      <h4>1.1 Beneficários:</h4>
      <p>Agricultores e Pecuaristas Familiares de municípios que aderirem ao Programa Estadual de Incremento da Qualidade Genética da Pecuária de Carne e Leite - DISSEMINA.</p>    
      <h2>1.2 Critérios para Seleção dos Municípios:</h2>
      <p>Os critérios para identificar os Munícipios que farão parte do Programa Dissemina seguem os seguintes parâmetros: - IDH: Cujo índice é formado através de dados de renda, saúde e educação dos municípios. - Regiões: Foram detectadas seis regiões consideradas carentes no que se refere a melhoramento genético e produtividade da pecuária. - Indicações Regionais: Os coordenadores regionais das Inspetorias Veterinárias e Zootécnicas da Secretaria da Agricultura Pecuária e Agronegócio identificaram em suas respectivas Supervisões os municípios que se enquadram nos critérios do programa. - Antigos clientes: Foi levado em conta os municípios que foram clientes da Central Rio-grandense de Inseminação Artificial (CRIA) e que deixam de inseminar ou que a diminuíram significativamente a inseminação devido interrupção do serviço da CRIA.</p>
      <h2>1.3 Critérios de Adesão dos Municípios:</h2>
      <p>Para aderir ao programa o município deverá ter Responsável Técnico, com formação na área de Medicina Veterinária, Zootecnia ou Técnicos Agrícolas e equipe de inseminadores devidamente capacitados. Para os responsáveis técnicos será exigido freqüência em Curso Preparatório de Responsáveis Técnicos a ser ofertado pelo Programa DISSEMINA com carga horária e conteúdo programático adequado aos objetivos do Programa. A comprovação da capacitação dos inseminadores se dará através da apresentação de certificado de aprovação em cursos de inseminação artificial, com carga horária mínima de 40 horas.</p>
      <h2>1.4 Critérios para seleção de propriedades pelos municípios</h2>
      <p>Os municípios deverão selecionar propriedades cujas características atendam o disposto na Lei Federal nº 11.326, de 24 de julho de 2006, que estabelece as diretrizes para a formulação da Política Nacional da Agricultura Familiar e Empreendimentos Familiares Rurais, e na Lei Estadual nº 13.515, de 13 de setembro de 2010, que Institui o Programa Estadual de Desenvolvimento da Pecuária de Corte Familiar, com a respectiva regulamentação do atual governo.Nesse sentido, entende-se como propriedade de agricultura familiar aquela que atenda simultaneamente- I - não detenha, a qualquer título, área maior do que 4 (quatro) módulos fiscais, com exceção de condomínio rural ou outras formas coletivas de propriedade, desde que a fração ideal por proprietário não ultrapasse 4 (quatro) módulos fiscais; II - utilize predominantemente mão-de-obra da própria família nas atividades econômicas do seu estabelecimento ou empreendimento; III - tenha renda familiar predominantemente originada de atividades econômicas vinculadas ao próprio estabelecimento ou empreendimento; IV - dirija seu estabelecimento ou empreendimento com sua família. Da mesma forma, entende-se como propriedade de pecuária Familiar, aquela que atenda simultaneamente as seguintes especificações: I - produção de bovinos e/ou caprinos e/ou bubalinos de corte e/ou ovinos; II - produção predominantemente familiar, podendo utilizar mão de obra contratada até 120 (cento e vinte) dias ao ano III - posse, a qualquer título, de propriedades rurais com área não superior a 300ha (contínua ou não) V - obtenção de, no mínimo, 70% (setenta por cento) da renda provinda da atividade pecuária e não agropecuária do estabelecimento, excluídos os benefícios sociais e os proventos previdenciários decorrentes de atividades rurais, residência na propriedade ou em local próximo.</p>
      <h2>1.5 Disponibilização de Materiais Genéticos</h2>
      <p>A disponibilização de materiais genéticos aos municípios que aderirem ao DISSEMINA será realizada pelo Centro de Biotécnicas Reprodutivas - CBR, localizado na Fepagro Campanha – Centro de Pesquisas Iwar Beckmann, localizado de Hulha Negra. O CBR, através da Central Riograndense de Inseminação Artificial – CRIA, disponibilizará inicialmente doses de sêmen bovino de raças de corte e leite. Num segundo momento, a partir da criação da Central Riograndense de Transferência de Embriões – CRTE, serão implementadas ações para a disponibilização de embriões à seleção de raças para a disponibilização das doses de sêmen bovino será realizada pelo CBR, levando-se em consideração as características zootécnicas dos rebanhos existentes no RS, bem como as características das propriedades, Os materiais genéticos disponibilizados pelo programa deverão atender a legislação do Ministério da Agricultura, Pecuária e Abastecimento, bem como as demais legislações correlatas, quanto aos procedimentos de obtenção, processamento, estoque e distribuição.</p>
      <h2>1.6 Gerenciamento e monitoramento</h2>
      <p>Para gerenciamento do programa será elaborado software que possibilite o monitoramento das ações do programa. O referido software deverá possibilitar a verificação de informações sobre as características da propriedade, em especial as relacionados às características do rebanho bovino e índices reprodutivos. O software também deverá possibilitar o registro de todas as ações realizadas pelo DISSEMINA na propriedade e no município, bem como a solicitação da quantidade de doses de sêmen pelos municípios. A disponibilização dessas informações em meio eletrônico facilitará o gerenciamento e a verificação dos resultados programa.</p>    
    </section>
  );
}

export default Sobre;
